-- Datos iniciales (seed): exactamente los equipos, jugadores y
-- calendario que ya tenia la app antes de tener base de datos.
-- Ejecutar UNA sola vez, despues de correr schema.sql.

insert into public.teams (id, name, logo_url, sort_order) values
  ('sinai', 'Sinaí', '/images/escudo_sinai.png', 0),
  ('bautista', '3ra Bautista', '/images/3ra_bautista.png', 1),
  ('corderito', 'El Corderito', '/images/el_cordero.png', 2),
  ('pedro', 'Pedro', '/images/pedro.png', 3),
  ('ligaevangelica', 'Liga Evangélica', '/images/liga_evangelica.png', 4),
  ('rocafuerte', 'Roca Fuerte', '/images/roca_fuerte.png', 5)
on conflict (id) do nothing;

insert into public.players (team_id, name, sort_order) values
  ('sinai', 'Frank Reina', 0),
  ('sinai', 'Erik Rodriguez', 1),
  ('sinai', 'Alexander Leyte', 2),
  ('sinai', 'Victor Falcón', 3),
  ('sinai', 'Ernesto Gonzalez', 4),
  ('sinai', 'Maikol Álvarez', 5),
  ('sinai', 'Jorge Popo', 6),
  ('sinai', 'Eliú', 7),
  ('sinai', 'Sergio Rodriguez', 8),
  ('sinai', 'Fermin Jiménez', 9),
  ('sinai', 'Cristian Quintana', 10),
  ('sinai', 'Dairon Morales', 11),
  ('sinai', 'Alexey', 12),
  ('sinai', 'Alexander Calzado', 13),
  ('sinai', 'Radamé', 14),
  ('bautista', 'Diego Ramírez', 0),
  ('bautista', 'Miguel Vargas', 1),
  ('bautista', 'Cristian León', 2),
  ('bautista', 'José Martínez', 3),
  ('bautista', 'Adrián Torres', 4),
  ('bautista', 'Kevin Salazar', 5),
  ('bautista', 'Luis Paredes', 6),
  ('bautista', 'Ángel Rojas', 7),
  ('bautista', 'Sergio Fuentes', 8),
  ('bautista', 'Pablo Jiménez', 9),
  ('bautista', 'Ricardo Soto', 10),
  ('bautista', 'Emanuel Reyes', 11),
  ('bautista', 'Óscar Luna', 12),
  ('bautista', 'Iván Delgado', 13),
  ('bautista', 'Gabriel Peña', 14),
  ('corderito', 'Juan Pérez', 0),
  ('corderito', 'David Suárez', 1),
  ('corderito', 'Josías Herrera', 2),
  ('corderito', 'Moisés Aguilar', 3),
  ('corderito', 'Eliezer Campos', 4),
  ('corderito', 'Santiago Cruz', 5),
  ('corderito', 'Daniel Flores', 6),
  ('corderito', 'Caleb Ortiz', 7),
  ('corderito', 'Aarón Ramírez', 8),
  ('corderito', 'Esteban Silva', 9),
  ('corderito', 'Joel García', 10),
  ('corderito', 'Samuel Rivas', 11),
  ('corderito', 'Mateo Torres', 12),
  ('corderito', 'Josué Luna', 13),
  ('corderito', 'Isaac Mendoza', 14),
  ('pedro', 'Pedro Hernández', 0),
  ('pedro', 'Lucas Morales', 1),
  ('pedro', 'Andrés Castillo', 2),
  ('pedro', 'Daniel Gómez', 3),
  ('pedro', 'Josué Ramírez', 4),
  ('pedro', 'David Torres', 5),
  ('pedro', 'Samuel Vargas', 6),
  ('pedro', 'Elías Cruz', 7),
  ('pedro', 'Jonathan Reyes', 8),
  ('pedro', 'Marcos Jiménez', 9),
  ('pedro', 'Isaac Rojas', 10),
  ('pedro', 'Caleb Herrera', 11),
  ('pedro', 'Joel Martínez', 12),
  ('pedro', 'Rubén Salazar', 13),
  ('pedro', 'Esteban López', 14),
  ('ligaevangelica', 'Pastor', 0),
  ('ligaevangelica', 'Rey', 1),
  ('ligaevangelica', 'Leordenis', 2),
  ('ligaevangelica', 'Josué', 3),
  ('ligaevangelica', 'Daineris', 4),
  ('ligaevangelica', 'José Landi', 5),
  ('ligaevangelica', 'Pinki', 6),
  ('ligaevangelica', 'Ángel', 7),
  ('ligaevangelica', 'Raúl', 8),
  ('ligaevangelica', 'Dayron', 9),
  ('ligaevangelica', 'Emanuel', 10),
  ('ligaevangelica', 'Samuel', 11),
  ('ligaevangelica', 'Samuel Cristian', 12),
  ('rocafuerte', 'David Gómez', 0),
  ('rocafuerte', 'Josué Torres', 1),
  ('rocafuerte', 'Samuel Ramírez', 2),
  ('rocafuerte', 'Daniel Herrera', 3),
  ('rocafuerte', 'Elías Cruz', 4),
  ('rocafuerte', 'Jonathan Vargas', 5),
  ('rocafuerte', 'Mateo Castillo', 6),
  ('rocafuerte', 'Caleb Jiménez', 7),
  ('rocafuerte', 'Andrés Rojas', 8),
  ('rocafuerte', 'Joel Mendoza', 9),
  ('rocafuerte', 'Isaac Pérez', 10),
  ('rocafuerte', 'Rubén Martínez', 11),
  ('rocafuerte', 'Marcos Luna', 12),
  ('rocafuerte', 'Esteban Salazar', 13),
  ('rocafuerte', 'Aarón Reyes', 14);

insert into public.matchdays (numero, titulo, fecha, badge, es_proxima) values
  (1, 'Jornada 1', 'Domingo 20/09/2026', null, true),
  (2, 'Jornada 2', 'Domingo 27/09/2026', null, false),
  (3, 'Jornada 3', 'Domingo 04/10/2026', null, false),
  (4, 'Jornada 4', 'Domingo 11/10/2026', null, false),
  (5, 'Jornada 5', 'Domingo 18/10/2026', null, false),
  (6, 'Jornada 6', 'Domingo 25/10/2026', null, false),
  (7, 'Jornada 7', 'Domingo 01/11/2026', null, false),
  (8, 'Jornada 8', 'Domingo 08/11/2026', null, false),
  (9, 'Jornada 9', 'Domingo 15/11/2026', null, false),
  (10, 'Jornada 10', 'Domingo 22/11/2026', null, false),
  (11, 'Jornada 11', 'Domingo 29/11/2026 • (Ida)', 'Semifinales', false),
  (12, 'Jornada 12', 'Domingo 06/12/2026 •  (Vuelta)', 'Semifinales', false),
  (13, 'Jornada 13', 'Domingo 13/12/2026 • Gran Final', 'Gran Final 🏆', false)
on conflict (numero) do nothing;

insert into public.matches (jornada_numero, orden, local_team_id, local_label, visitante_team_id, visitante_label, hora) values
  (1, 0, 'sinai', null, 'rocafuerte', null, '3:30 pm'),
  (1, 1, 'bautista', null, 'ligaevangelica', null, '4:20 pm'),
  (1, 2, 'corderito', null, 'pedro', null, '5:10 pm'),
  (2, 0, 'sinai', null, 'ligaevangelica', null, '3:30 pm'),
  (2, 1, 'rocafuerte', null, 'pedro', null, '4:20 pm'),
  (2, 2, 'bautista', null, 'corderito', null, '5:10 pm'),
  (3, 0, 'sinai', null, 'pedro', null, '3:30 pm'),
  (3, 1, 'ligaevangelica', null, 'corderito', null, '4:20 pm'),
  (3, 2, 'rocafuerte', null, 'bautista', null, '5:10 pm'),
  (4, 0, 'sinai', null, 'corderito', null, '3:30 pm'),
  (4, 1, 'pedro', null, 'bautista', null, '4:20 pm'),
  (4, 2, 'ligaevangelica', null, 'rocafuerte', null, '5:10 pm'),
  (5, 0, 'sinai', null, 'bautista', null, '3:30 pm'),
  (5, 1, 'corderito', null, 'rocafuerte', null, '4:20 pm'),
  (5, 2, 'pedro', null, 'ligaevangelica', null, '5:10 pm'),
  (6, 0, 'rocafuerte', null, 'sinai', null, '3:30 pm'),
  (6, 1, 'ligaevangelica', null, 'bautista', null, '4:20 pm'),
  (6, 2, 'pedro', null, 'corderito', null, '5:10 pm'),
  (7, 0, 'ligaevangelica', null, 'sinai', null, '3:30 pm'),
  (7, 1, 'pedro', null, 'rocafuerte', null, '4:20 pm'),
  (7, 2, 'corderito', null, 'bautista', null, '5:10 pm'),
  (8, 0, 'pedro', null, 'sinai', null, '3:30 pm'),
  (8, 1, 'corderito', null, 'ligaevangelica', null, '4:20 pm'),
  (8, 2, 'bautista', null, 'rocafuerte', null, '5:10 pm'),
  (9, 0, 'corderito', null, 'sinai', null, '3:30 pm'),
  (9, 1, 'bautista', null, 'pedro', null, '4:20 pm'),
  (9, 2, 'rocafuerte', null, 'ligaevangelica', null, '5:10 pm'),
  (10, 0, 'bautista', null, 'sinai', null, '3:30 pm'),
  (10, 1, 'rocafuerte', null, 'corderito', null, '4:20 pm'),
  (10, 2, 'ligaevangelica', null, 'pedro', null, '5:10 pm'),
  (11, 0, null, '1° Clasificado', null, '4° Clasificado', '3:30 pm'),
  (11, 1, null, '2° Clasificado', null, '3° Clasificado', '4:30 pm'),
  (12, 0, null, '4° Clasificado', null, '1° Clasificado', '3:30 pm'),
  (12, 1, null, '3° Clasificado', null, '2° Clasificado', '4:30 pm'),
  (13, 0, null, 'Ganador Semifinal 1', null, 'Ganador Semifinal 2', '4:00pm');
